development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: postgres://fmrpkdbsiaygpx:32b30fa3f4de0884049de6a74bad805f1777a3aa1d4272a2bc7589f80c02fc3b@ec2-54-83-204-6.compute-1.amazonaws.com:5432/ded45oe47kj551
  channel_prefix: nameofapp_production
